language: go
go:
- tip
before_install:
- go get github.com/Sirupsen/logrus
- go get github.com/gorilla/websocket
git:
  submodules: false
deploy:
  provider: heroku
  api_key:
    secure: 65f188af-7e21-4083-9aa7-75aa48b3905d


